"""initial schema

Revision ID: 8991597c1c94
Revises: 
Create Date: 2026-02-12 16:54:58.723480
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8991597c1c94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PLANNING', 'DISCUSSING', 'REFLECTING', 'SYNTHESIZING', 'COMPLETED', 'FAILED', name='discussionstatus'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('max_rounds', sa.Integer(), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('HOST', 'PANELIST', 'CRITIC', name='agentrole'), nullable=False),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.Enum('HOST', 'PANELIST', 'CRITIC', name='agentrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('agent_configs')
    op.drop_table('discussions')
    # ### end Alembic commands ###
